[package]
name = "ramstack"
version = "1.0.1"
authors = ["levi@a2n.finance"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
ramstack='131af981c6ee5ee61c9440c5254f0448aef8e5cb8d2c321ff3024490c71eaaaa'

[dev-addresses]

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../../aptos-core/aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
